-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE,
    isVerified BOOLEAN DEFAULT FALSE,
    verificationToken VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    service VARCHAR(255) NOT NULL,
    details TEXT,
    phone VARCHAR(32),
    status VARCHAR(16) DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- GALLERY TABLE
CREATE TABLE IF NOT EXISTS gallery (
    id SERIAL PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    title VARCHAR(255) NOT NULL,
    mediaType VARCHAR(16) DEFAULT 'image' CHECK (mediaType IN ('image', 'video')),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RATINGS TABLE
CREATE TABLE IF NOT EXISTS ratings (
    id SERIAL PRIMARY KEY,
    stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
    description TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 